# Generated by Django 4.0.6 on 2022-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('department', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=2)),
                ('division', models.CharField(max_length=1)),
            ],
        ),
    ]
