# Generated by Django 4.0.6 on 2022-10-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_attendance_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
