# Generated by Django 4.0.6 on 2022-10-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_attendance_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=2)),
                ('division', models.CharField(max_length=1)),
                ('subject', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_image',
            field=models.ImageField(null=True, upload_to='Attendance_Images/'),
        ),
    ]
