# Generated by Django 4.0.6 on 2022-10-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_student_attendance_alter_attendance_attendance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendance',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
    ]
